ggto/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :recipes
  get 'welcome/index'

  root 'welcome#index'

  get 'myrecipe' => 'recipes#myrecipe'
  get 'recipeof/:user_id' => 'recipes#recipeof', :as => "recipeof"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ggto/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

ggto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ggto/app/models/recipe.rb
class Recipe < ApplicationRecord
  validates  :nam_recipes, presence: true
  validates  :ingredients, presence: true
  validates  :preparation, presence: true
  validates  :state, presence: true

  belongs_to :user

  mount_uploader :photo, ImagUploader
end

ggto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :recipes
end

ggto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ggto/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [ :index, :show ]

def recipeof
  @user_id = params[:user_id]
  @user = User.find(@user_id)
  @recipes = @user.recipes
end


  def myrecipe
    @recipes = current_user.recipes
  end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:nam_recipes, :ingredients, :preparation, :preparation_time, :photo, :state, :description)
    end
end

ggto/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ggto/app/helpers/application_helper.rb
module ApplicationHelper
end

ggto/app/helpers/recipes_helper.rb
module RecipesHelper
end

ggto/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ggto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gastronomia Guanajuato</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/masonry/4.1.0/masonry.pkgd.min.js">

    </script>
  </head>

  <body>
    <%=  render 'layouts/shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

ggto/app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px;" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= welcome_index_path %>">Inicio</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Bebidas </a></li>
        <li><a href="<%= recipes_path %>">Comidas</a></li>
        <li><a href="<%= myrecipe_path %>">Mis recetas</a> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><a href="<%=  new_user_session_path %>">Ingreso</a></li>
          <li><a href="<%=  new_user_registration_path %>">Registro</a></li>
        <% else %>
          <li><a href="<%=  destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ggto/app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.label :nam_recipes, 'Nombre' %>
      <%= f.text_field :nam_recipes, :class => 'form-control', :placeholder => "Nombre de la Receta" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :ingredients, 'Ingredientes' %>
      <%= f.text_area :ingredients, :class => 'form-control', :placeholder => "Ingredientes", :rows => "10", :cols => "30"  %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :preparation, 'Preparacion' %>
      <%= f.text_area :preparation, :class => 'form-control', :placeholder => "Modo de Preparacion", :rows => "10", :cols => "30"  %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :preparation_time, 'Timepo de Preparacion (min)' %>
      <%= f.text_field :preparation_time, :class => 'form-control', :placeholder => "Tiempo de Preparacion"  %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :photo, 'Foto' %>
      <%= f.file_field :photo, :class => 'form-control', :placeholder => "Foto"  %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :state, 'Estado' %>
      <%= f.text_field :state, :class => 'form-control', :placeholder => "Estado"  %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :description, 'Descripción' %>
      <%= f.text_area :description, :class => 'form-control', :placeholder => "Descripción", :rows => "10", :cols => "30"  %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary" %>
  </div>

<% end %>

ggto/app/views/recipes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Editar recetas</h1>

      <%= render 'form', recipe: @recipe %>

      <%= link_to 'Show', @recipe %> |
      <%= link_to 'Back', recipes_path %>
    </div>
  </div>
</div>

ggto/app/views/recipes/index.html.erb
<div id="container">
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

    <% @recipes.each do |recipe| %>
      <div class="item" style="width: 250px">
        <div class="thumbnail">
        <%= recipe.nam_recipes %> <br />
        <%= recipe.ingredients %> <br />
        <%= recipe.preparation %> <br />
        <%= recipe.preparation_time %> <br />
        <%= recipe.state %> <br />
        <%= recipe.description %> <br />
        <%= image_tag(recipe.photo, :class => 'img-responsive') %>
          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', recipe, :class => 'btn' %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => 'btn' %>
            <% if user_signed_in? %>
            <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>


</div>

<script type="text/javascript">
  var $container = $('#container');
  // initialize
  $container.masonry({
    columnWidth: 200,
    itemSelector: '.item'
  });
  $(windows).load(function(){
    var $container = $('#container');
    // initialize
    $container.masonry({
      columnWidth: 200,
      itemSelector: '.item'
    });
  })
</script>

<hr style="border-top: 1px solid #ff5412">

<% if user_signed_in? %>
    <%= link_to 'New Recipe', new_recipe_path %>
<% end %>

ggto/app/views/recipes/myrecipe.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Mis Recetas</h1>

  <% @recipes.each do |recipe| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= recipe.nam_recipes %> <br />
          <%= recipe.ingredients %> <br />
          <%= recipe.preparation %> <br />
          <%= recipe.preparation_time %> <br />
          <%= recipe.state %> <br />
          <%= recipe.description %> <br />
          <%= image_tag(recipe.photo, :class => 'img-responsive') %>
          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', recipe, :class => 'btn' %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>


  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Recipe', new_recipe_path %>
  <% end %>
</div>

ggto/app/views/recipes/new.html.erb
<div class="container">
  <h1>Agregar Receta</h1>
  <div class="row">
    <div class="col-md-6">
      <%= render 'form', recipe: @recipe %>
    </div>
  </div>
  <p><%= link_to 'Back', recipes_path %></p>
</div>

ggto/app/views/recipes/recipeof.html.erb
<%= @user_id %>
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Recipes</h1>

  <% @recipes.each do |recipe| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= recipe.nam_recipes %> <br />
          <%= recipe.ingredients %> <br />
          <%= recipe.preparation %> <br />
          <%= recipe.preparation_time %> <br />
          <%= recipe.state %> <br />
          <%= recipe.description %> <br />
          <%= image_tag(recipe.photo, :class => 'img-responsive') %>
          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', recipe, :class => 'btn' %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>


  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Recipe', new_recipe_path %>
  <% end %>
</div>

ggto/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nam recipes:</strong>
  <%= @recipe.nam_recipes %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @recipe.preparation %>
</p>

<p>
  <strong>Preparation time:</strong>
  <%= @recipe.preparation_time %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@recipe.photo, :style => 'width:150px') %>
</p>

<p>
  <strong>State:</strong>
  <%= @recipe.state %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
<%= link_to "Mas Recetas del mismo Usuario" %> #, recipeof_path(@recipe.user.id)

ggto/app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 id="titulo 1"> Titulo </h1>
    <a href="http://en1mes.com">En un mes</a>
    <a href="http://en1mes.com" class="btn btn-default ">
      En un mes otra pagina
    <span class="glyphicon glyphicon-leaf" style="color: green"></span>
    </a>
  </div>
</div>
<div class="container">
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
      <h2 style="display: inline">Example page</h2>
      <span class="label label-default">New</span>
    </div>
    <p> El Ford Mustang es un muscle car de la caFalcon (Estados Unidos)|Ford Falcon]],
    un vehículo del segmento D.1 Fue introducido al mercado el 17 de abril de 1964.
    2 El Mustang de 1965 fue el modelo más exitoso desde el Ford A.,
    3 así mismo Mustang es la tercera saga de Ford más antigua, cuyos modelos han sufrido
    numerosas transformaciones hasta llegar a la actual sexta generación.
  <p>
    El Mustang dio origen a una nueva clase de vehículo estadounidense denominado
    «pony car» — un coupé deportivo con largo capó delantero y corta parte trasera.
    —4 Ha tenido entre sus máximos rivales al Chevrolet Camaro de GM,5 el Javelin de
    AMC,6 el Dodge Challenger, y el renovado Plymouth Barracuda de Chrysler.7
    También ha inspirado a modelos como el Toyota Celica y Ford Capri, que fueron
    importados posteriormente a Estados Unidos.
  </p>
  </div>
  <div class="col-md-4">
    <div class="page-header">
      <h2 style="display: inline">Example page</h2>
      <span class="label label-default">New</span>
    </div>
    <p> El Ford Mustang es un muscle car de la caFalcon (Estados Unidos)|Ford Falcon]],
      un vehículo del segmento D.1 Fue introducido al mercado el 17 de abril de 1964.
      2 El Mustang de 1965 fue el modelo más exitoso desde el Ford A.,
      3 así mismo Mustang es la tercera saga de Ford más antigua, cuyos modelos han sufrido
      numerosas transformaciones hasta llegar a la actual sexta generación.
    <p>
      El Mustang dio origen a una nueva clase de vehículo estadounidense denominado
      «pony car» — un coupé deportivo con largo capó delantero y corta parte trasera.
      —4 Ha tenido entre sus máximos rivales al Chevrolet Camaro de GM,5 el Javelin de
      AMC,6 el Dodge Challenger, y el renovado Plymouth Barracuda de Chrysler.7
      También ha inspirado a modelos como el Toyota Celica y Ford Capri, que fueron
      importados posteriormente a Estados Unidos.
    </p>
  </div>


  <div class="col-md-4">
    <div class="page-header">
      <h2 style="display: inline">Example page</h2>
      <span class="label label-default">New</span>
    </div>
    <p> El Ford Mustang es un muscle car de la caFalcon (Estados Unidos)|Ford Falcon]],
      un vehículo del segmento D.1 Fue introducido al mercado el 17 de abril de 1964.
      2 El Mustang de 1965 fue el modelo más exitoso desde el Ford A.,
      3 así mismo Mustang es la tercera saga de Ford más antigua, cuyos modelos han sufrido
      numerosas transformaciones hasta llegar a la actual sexta generación.
    <p>
      El Mustang dio origen a una nueva clase de vehículo estadounidense denominado
      «pony car» — un coupé deportivo con largo capó delantero y corta parte trasera.
      —4 Ha tenido entre sus máximos rivales al Chevrolet Camaro de GM,5 el Javelin de
      AMC,6 el Dodge Challenger, y el renovado Plymouth Barracuda de Chrysler.7
      También ha inspirado a modelos como el Toyota Celica y Ford Capri, que fueron
      importados posteriormente a Estados Unidos.
    </p>
  </div>
</div>

<hr>
<br>
<a href="http://en1mes.com">
  <img src="http://imganuncios.mitula.net/ford_mustang_fast_back_v8_289_automatico_a%C3%B1o_1967_ford_a_mxn_285000_en_preciolandia_mexico_8m7wto_1760130445811572122.jpg"
  class="img-responsive">
</a>
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>
</div>